### ISSUE TITLE
Add type declarations for version 4.3.0

### ISSUE THREAD

**Issue by pallosp** [tomwanzek/d3-v4-definitelytyped#131]
The latest d3 update brought 3 new functions (VoronoiDiagram.find, d3.geoIdentity, d3.geoGraticule10) and new arguments to d3.geoPath.

Changelog: https://github.com/d3/d3/releases/tag/v4.3.0

**Comment by tomwanzek** [comment]
I am aware  of the changes, the definitions in this repo have been migrated to DefinitelyTyped (`types-2.0` branch). There you will find the latest available definitions, which are also the ones published to npm @types. All issues, enhancements related to the definitions in this repo are now managed on DT.

I have already updated the definitions for d3-voronoi to version 1.1.0 and published them.

I have opened an issue for [**d3-geo 1.3.1** DT 12296](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12296).

Should you want to expedite the process of updating the d3-geo definitions, feel free to submit a PR against the DefinitelyTyped **types-2.0** branch. Please, ensure to @-mention the primary author and myself so we can review/approve,, although I think there might be a bot doing it automagically now.

Otherwise, I will see what I can do at the earliest opportunity to expedite.

Updating the definitions for **d3** to version 4.3 is a simple chore,I can quickly do once d3-geo is in.
