### ISSUE TITLE
Decide on best BaseType for Selection/Transition elements

### ISSUE THREAD

**Issue by tomwanzek** [tomwanzek/d3-v4-definitelytyped#2]
In general, the elements of a selection will be DOM elements (HTML or SVG.) These could be captured with the current constraint the `type BaseType = Element` for `d3-selection`, `d3-transition` and DOM event related packages like `d3-drag` and `d3-zoom`.

However, _EnterElement_ (or _EnterNode_) elements constituting the group elements of the `enter()` selection after a data join do not meet this minimal requirement (see `EnterElement` interface in d3-selection.

Also, there may be use cases, albeit exceptional, where the constituent element of a `selection` (`transition`), is of a general nature, i.e. could be `any`. In which case, some methods of the `Selection` or `Transition` will not work, as the element misses properties/methods which are internally used by the respective D3 modules.

See the  [d3- selection issue](https://github.com/d3/d3/issues/2854) and the [DOM-to-Canvas Example](http://bl.ocks.org/mbostock/1276463).

As the `Selection` and `Transition` interfaces and related selection methods are generisized, not explicitly stating the type, may use type inference, based on typed arguments or return values to determine the type of `this` where it is tied to the element type. If inference is not possible, the `BaseType` would be the default value.

So, while strictly a `type BaseType = Element` or something like`interface BaseType extends Node, QuerySelector {}` would be too restrictive, it may be preferable in 99% (?) of use cases due to the default behavior.

**Comment by tomwanzek** [comment]
The other related example by Mike Bostock is [OMG Particle II](https://bl.ocks.org/mbostock/9539958).
It uses a plain non-DOM object as a starting point.

**Comment by tomwanzek** [comment]
Decoupled element base type for d3-drag from d3-selection, same will apply to d3-zoom. Issue is irrelevant to d3-brush.

**Comment by tomwanzek** [comment]
If the `BaseType` underlying `Selection` and `Transition` is relaxed. Then `NodeListOf` should be replaced with a new interface `ArrayLike` or similar to circumvent the inherent  constraint on node list elements.

**Comment by devgru** [comment]
> The other related example by Mike Bostock is OMG Particle II.
> It uses a plain non-DOM object as a starting point.

IMHO This case is not relevant, selection there was used to start transition, it was the only way to do it in v3. For v4 one can simply run `d3.transition()` and it will work.

**Comment by tomwanzek** [comment]
@devgru Thanks for your perspective above.

After a second review, I have chosen to walk a middle ground as follows:
1. I replaced `NodeListOf<...>`  with a new interface `ArrayLike<...>` where the former was too restrictive. The result is that passing in an `HTMLCollectionOf<...>` no  longer throws an error (with ES6 target). Also `EnterElement` is now a permissible element type, which allows the next item
2. The `BaseType` for `Selection` and `Transition` has now been set to `Element | EnterElement` which allows the `enter()` selection have group elements of type EnterElement in accordance with the D3 design.
3. There is a commented out alternative line `export type BaseType = any;` , which, when manually toggled, can serve to accommodate the edge cases. The change under 1. allows this to be used (with care) without compile errors  which would have been implied by the `... | NodeListOf<...>` constraint.

This seems to be a decent compromise.

**Comment by tomwanzek** [comment]
As per comment from @zbjornson `d3.select(window)` should be supported.

**Option 1:** Expand the union type alias `BaseType = Element | Window | EnterElement`

**Option2:** Generalize all the way to `BaseType = any` (i.e. explicit `any`)

Up for discussion, preference indication.

**Comment by devgru** [comment]
IMHO **Option 1** is preferrable, Window is a special case, mostly used to handle resize events.

**Comment by tomwanzek** [comment]
Thanks @devgru . I will leave this open slightly longer to see if anyone else wants to chime in. Then I will make the resulting change in this repo and on the side of DefinitelyTyped (if the current PR is still not merged by then, I will amend, otherwise, will do a follow-up PR.)

**Comment by jnm2** [comment]
@tomwanzek @devgru I remember @mbostock saying that he intended you to be able to select anything, specifically that he did not want it to be limited (https://github.com/d3/d3/issues/2854#issuecomment-226317109):

> More generally, you’re allowed to create selections of things (Selection<T>) that are not elements using d3.select(T) and d3.selectAll(Array<T>). As long as you don’t try to treat non-elements as elements, the selection and any operations on it are valid. For example [OMG Particles II](https://bl.ocks.org/mbostock/9539958) selects a plain object for the purpose of creating a transition that is then rendered to Canvas. That’s a bit of an edge case, and rarely needed, but I don’t want to strictly limit selections to DOM elements.

To me that's a good argument in favor of explicit `any` because explicit `any` documents the fact that you are intended to give any kind of object. A more restrictive type would be misleading.

**Comment by tomwanzek** [comment]
As with many things in real life this is not a clear-cut situation. The reason why I am sitting firmly on the fence when it comes to this tradeoff, is imply the following.

I wholly understand Mike's desire for generality. Although, he clearly acknowledges that the matter is

> ...an edge case, and rarely needed...

Working only in Javascript allows tremendous flexibility, but comes at a massive cognitive burden for developers, testers, API consumers etc to understand intent and failure modes.

Personally, I found Javascript rather insufferable until TypeScript came along and enabled work at scale/with complex scope. But the premise of TypeScript is the ability to _predictably rely_ on the fact that, if a generic sets a certain 'minimal requirement' on permissible types, any type meeting the requirement will allow the templated object to work as expected.

What is, IMHO, actually more misleading, is to portray a `Selection` (or `Transition`)  as fully functional across all exposed methods, with `any` as the `BaseType`. Most of the methods implemented on the selection internally make assumptions about certain methods/properties being available on the selected element (or the 'parent' in the selection chain for sub-selections). This is even the case with the `EnterElement` type, returned by the `enter()` Selection.

Thus, code will compile fine and later fail at runtime in the guts of **d3-selection** or **d3-transition** (and, I suspect, it will not always be quick to troubleshoot).

The question is, whether serving a rare, exceptional edge case is worth giving up the stronger minimal (and default) typing imposed by Option 1.

My judgment would tell me Option 1 serves the vast majority of circumstances in a better way within the context of TypeScript's mental model. The edge case might be sufficiently served by manually toggling the `BaseType` to `any` for the particular use case as suggested in [this comment](https://github.com/tomwanzek/d3-v4-definitelytyped/issues/2#issuecomment-234150646). It becomes a conscious choice that should trigger the additional care.

One of my questions is, are there any other more standard scenarios, where `Element | Window | EnterElement` would be too restrictive?

**Comment by jnm2** [comment]
> Personally, I found Javascript rather insufferable until TypeScript came along and enabled work at scale/with complex scope. But the premise of TypeScript is the ability to predictably rely on the fact that, if a generic sets a certain 'minimal requirement' on permissible types, any type meeting the requirement will allow the templated object to work as expected.

Well said and I could not agree more!

In my mind though, that decision has already been made by the library. Sometimes the code will _not_ fail at runtime with an `any` object. I agree that it's poor API design with cognitive load, but is it the place of the type definition to put idealistic restrictions on the intended usage of the library?

Also, allowing `Window` will run into the same objections you had for `any`. If you treat a `Window` selection as an element selection, you will fail at runtime for some things just like if you treat an `any` selection as an element selection. Drawing an arbitrary line at `Window` is inconsistent.

Uncommenting the line is also not going to be a great option for those of use using NuGet. It'll get wiped out without warning every time the package is restored.

**Comment by jnm2** [comment]
Here's an alternative: what if you had overloads of `select` that had a different return type depending on whether you use the `any` overload, the `Window` overload, or an element overload? It's extra typing work but would be rewarding because it could prevent all the fail-at-runtime scenarios while still providing fine-grained API.

I'm suggesting that as a long term goal. You have a better grasp of TypeScript but I'd be willing to do the work towards that goal if you think it's feasible. I'm personally fine with whatever you do for the first release.

**Comment by tomwanzek** [comment]
@gustavderdrache @Ledragon @ocombe @zbjornson Can you have a look at this issue as well. Would be interested in your respective takes so we can close this off, w.r.t. options 1 or 2.

**Comment by gustavderdrache** [comment]
I have a short reply and a long reply, in that order.

### The short reply:

Don't let perfect be the enemy of the good. Let's stick with `BaseType` being a union of `Element` and `EnterElement`. We have to accept that the underlying JavaScript library is more flexible than we can give a type too, and that's okay.

That having been said, the simplest fix would be to weaken the `Element` requirement to `EventTarget`.

**The pros**:
- This allows `window` and `document` to Just Work™
- This also allows a pattern that has bitten me a few times with the v3 defns:
  
  ```
  d3.select('p')
    .append(() => document.createTextNode("I'm a node!"));
  ```

**The cons**:
- For any non-`Element` `EventTarget`, we can't guarantee that things like `attr`, `style`, or `classed` will work.

### The long reply:

I'm actually not keen on adding either `Window` or even `Document` to the  `BaseType` union, because TypeScript's entire purpose is to keep code that you _know_ will crash at runtime from being accepted at compile time:

```
> d3.select(window).attr('foo')
TypeError: r.getAttribute is not a function(…)
```

The v3 d.ts files allow this because `d3.select`'s overloads accept either `EventTarget` or `string`. But now that we're parameterizing by the kind of element, I think that it would simply be best to require an `any` cast here, which I argue is a valid use case because `foo as any` can be read as an opt-out of type checking:

``` typescript
let bad = d3.select(window); // This may not do what you expect
let good = d3.select(window as any); // I know what I'm doing
```

The problem with adding overloads is that while `d3.select(window).on('foo', ...)` works, this won't:

```
d3.select({}).on('foo', () => {});
TypeError: this.addEventListener is not a function(…)
```

That would result in _four_ overloads, based on the capabilities of the passed-in object:
1. `d3.select(thing: Object)`, for which only the `property` method is guaranteed to work,
2. `d3.select(thing: EventTarget)`, for which `property` and `on` are guaranteed to work,
3. `d3.select(selector: string)`, for which all methods work
4. `d3.select(element: BaseType)`, for which all methods work

And if you _really_ want to get specific, the `Selection` interface really has a plethora of sub-interfaces based on the structure of the selected element (Does it have `getAttribute` and `setAttribute`? Does it have a `style` property that is a `CSSStyleDeclaration`? ... and so on). I will acknowledge the usefulness of such a thing, but the cost of testing and maintaining that many overloads worries me.

It only gets more awkward when you have to account for things D3 does under the covers for better browser capability: you can't use `Selection.filter`  unless your Element prorotype has `matches`. (Or `mozMatchesSelector`. Or `webkitMatchesSelector`. Or `msMatchesSelector`...).

Hmm.... this was probably way too much information.

**Comment by mbostock** [comment]
> IMHO This case is not relevant, selection there was used to start transition, it was the only way to do it in v3. For v4 one can simply run d3.transition() and it will work.

No; `d3.select({}).transition()` and `d3.transition()` are different; [d3.transition](https://github.com/d3/d3-transition#transition) creates a transition on document.documentElement, so it will interrupt any other active transition on the document element when it starts. That‘s relevant for the particle system because you want more than one particle active at a time.

However, there are perhaps two cleaner solutions to selecting a plain object: you could use d3.transition but then give each transition a unique name so they don’t interrupt each other, or you could avoid transitions altogether and use d3.timer and an in-memory queue of particles. The latter is probably the cleanest approach since the DOM isn’t really needed for a particle system.

I think it would be reasonable to ignore the possibility of Selection<Object> for the purposes of a TypeScript definition if it has too many drawbacks against the much more common case of Selection<Element>—it is an edge case with some potentially-useful applications, but it is rare. I like the idea that the Selection interface explicitly documents what methods it requires on implementing objects (so that you could, say, implement a virtual DOM on top of WebGL), but it could be onerous to maintain!

Is it possible in TypeScript to allow Selection<Window>.on but not Selection<Window>.attr? Are there generics? Or would it be d3.select(Window) returns WindowSelection while d3.select(string) returns ElementSelection?

**Comment by tomwanzek** [comment]
Hi All,

Thanks for the additional input (in particular @mbostock taking some time out of his already busy schedule). Mike could you kindly expand on the virtual DOM WebGL use case you have in mind?

From a level-setting perspective, the new definitions for the `Selection` and `Transition` interfaces are driven by four generics: 
1. A generic corresponding to the type of _element_ in the selection (**groups**)
2. A generic corresponding to the type of datum associated with a selected element as per 1.
3. A generic corresponding to the type of _element_ in the **parents** property of the selection
4. A generic corresponding to the type of datum associated with a **parents** element as per 3.

The `BaseType` discussed above  puts a constraint on 1. and 3. This applies to selections as well as transitions. (I have decoupled the constraint for d3-drag and d3-zoom already, as the degree of generality/flexibility for the selections/transitions used in conjunction with those behavior is less than what we are discussing here.)

The top-level selection methods `select(...)` and `selectAll(...)` are not the only ones which affect the generics corresponding to the elements (i.e. 1. and/or 3.) . There are also sub-selections (`select` and `selectAll`), `append`, `insert`, and `enter`.

I have to go through some of the considerations related to multiple interfaces with a bit more care to respond fully. Other than maintainability and usability. But in general I think the challenge would be to address all the scenarios, given that the all selection/transition methods have different constraints on available methods,
- addEventListener
- querySelector/querySelectorAll
- setAttribute
- appendChild
- etc.

Mike has the best of the top of his head insight into which methods make what assumption about available methods on the selected elements.

I think `window` came in particular for folks listening for resize events and the like (Something I tend to capture elsewhere when using Angular, but that is not the general intent of D3).

Mike has simply managed to pack a big punch into a very flexible, small piece of code :smile:

So the VirtualDOM/WebGL scenario might be of interest and I did not have time to consider it...

**Comment by Ledragon** [comment]
I just caught up with all this very interesting talk, I hope I will manage to make a relevant comment (otherwise, throw tomatoes at me).

I already used D3 v3 together with AngularJS (1.x) in directives, to create element via the [link](https://docs.angularjs.org/api/ng/service/$compile#-link-) function, and selecting my DOM element using the `iElement` argument of the link function (typed as `JQuery` in the [AngularJS type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/angularjs/angular.d.ts) ). Would this case be covered by the provided types? I don't know the exact underlying properties of the `JQuery` type, so unsure if it matches `Element` or `BaseElement`.

I think including `Window` type makes sense, as I think it would generate less frustration than having to cast it to any every time someone wants to use it (I am not so sure or the rarity of the use case). I would however not allow the `any` type, and go the way suggested by @gustavderdrache and force the user to cast to `any` when he wants to use one of the not-supported types.

**Comment by tomwanzek** [comment]
Alright, after letting this issue simmer for a little (and getting some other work done), here are a couple of (hopefully :wink: ) final considerations.

## Usage with Angular

@Ledragon thanks for raising the Angular question. Here is my take on it:

### Angular 1.x/JQuery

The `element` argument passed into the `link` function is something like `IAugmentedJQuery` or `JQuery`. In either case the key issue is that, when used with `d3.select(element[0])` the returned type is of element[0] is always `HTMLElement`. This problem is due to the Angular 1.x/JQuery definitions and occurs even, if the bound DOM element is actually an svg-type element. So as far as I can see, one would have to fool a selection of e.g. an SVGSVGElement: `let d3SVG = d3.select<SVGSVGElement, Datum>(<any>element[0])` to have the correct `this` typing in callbacks of the selection. Again, this is a fallout of how the JQuery definitions are written. Note that, `HTMLElement` is not castable to `SVGElement`, thus the playfake with `any`.

### Angular 2

Assuming one wants to build an Angular 2 Component/Directive using Angular 2 `elementRef: ElementRef` injected into the constructor., then `elementRef.nativeElement` would be used as the element passed into d3.select(...). Note that, as per Angular 2 `ElementRef.nativeElement` is of type `any` or `null`, if no native DOM element can be accessed. So use/casting of `ElementRef.nativeElement` e.g. with a SVGSVGElement selection, would require care and/or additional custom typeguards.

## Creating Separate Interfaces

Initially I considered creating separate, reduced interface to accommodate the `EnterElement` scenario apart from an `Element`-based general purpose interface.

As a matter of general course to addressing the various scenarios  discussed above, the strategy of creating "alternative" interfaces and all the conditioning signatures seems to place too high a burden on readability let alone maintainability. The latter point is exacerbated by the fact that the "alternative" interfaces/signatures would have to be consistently maintained across the interface augmentations e.g. in **d3-transition** and **d3-selection-multi** (or any other potential future extending modules) as well.

## BaseType Constraint

As @mbostock pointed out above, some of the edge cases, may be addressable with alternative means.

At the present time, the most pragmatic approach seems to be the following:
- extend the type alias to allow for `Window` for those who use it for listening to window events, i. e. `type BaseType = Element | EnterElement | Window`. This way there is an additional convenience for those working without additional frameworks like Angular on a given project.
- Accept the reality that for `EnterElement` and `Window` selections, there is additional care required to prevent runtime errors, which do not cause compile time errors. In a follow-up step that adds JSDoc comments, these "cautionary notes" could be added in to raise awareness.
- Wait and see, if specific issues are created with clear use cases by folks who use D3 and TypeScript jointly.

That being said, if someone has the wish and bandwidth to dive deeper into defining a minimally viable interface (i.e. shed from `Element`, what is not required to meet the internal requirements of `Selection` and/or `Transition` for all methods to be well defined.), then a follow-up PR is welcome. I guess, this would boil down to a minimally viable interface for a custom virtual DOM of sorts.

Unfortunately, as always in life, for now, I am afraid, I need to draw a line somewhere.

**Comment by tomwanzek** [comment]
I am going to close this for now. Should anything new arise, more than willing to revisit. :smile:
