### ISSUE TITLE
How to define functions with enhanced this

### ISSUE THREAD

**Issue by ocombe** [tomwanzek/d3-v4-definitelytyped#32]
I tried the current type definitions with the enhanced "this", but I get a lot of errors in my code from tslint because of "argument type function is not assignable to parameter type this"

Ex with:

```
d3.selectAll('div').each(function() {
  // ...
})
```

How am I supposed to define the "this" here to avoid this error? Is it just a problem of tslint not being updated to 1.9 (or 2.0) yet?

**Comment by tomwanzek** [comment]
I disabled tslint. Should be related to tslint not yet supporting the `this`-typing for function definitions of TS 1.9+.

**Comment by ocombe** [comment]
Damn :(
For now I edited your typings to not use the "this", because otherwise I won't see the errors until I save my documents and that's a problem for me :)

**Comment by tomwanzek** [comment]
I am almost finished working through the first cut of d3-hierarchy. Then I will will refocus on the testing side of things.

I have a few testing files in my local repo, which I have not pushed yet, i.p. for d3-selection/d3-transition.

One fallout of the initial cut of testing will be the following, I intend to create a separate branch with stripped-down versions of the typings (no `this` function typing and related generics) unless I create a pull request on DefinitelyTyped right away.

But since there are a few quirks I came across when writing the drafts, such as typing-related cross-module dependencies, which are not D3 source code dependencies. I might go the open issue route first.

**Comment by tomwanzek** [comment]
I added the bulk of the d3-selection tests, which show how to use the `this` typing. They compile without errors using the grunt task with the dev-dependency typescript@next. Where indicated with 'fails' in commented out code segments, uncommenting the respective block will create compile time errors which are considered intentionally created.

Will complete the data-join tests and event-related tests as next step.

**Comment by ocombe** [comment]
Just to let you know that tslint now supports typescript 2.0 :-)

**Comment by tomwanzek** [comment]
Thanks for the info! Will have a quick check-up on the repo toolchain (bring in  my usual grunt task and need to check the tslint plugin for VS Code. Would be nice :smile:!

**Comment by tomwanzek** [comment]
Done! TS Lint in place and linted
